Repository visuanalytics/visuanalytics, pull requests merged in 2021-04, with the labels that each got.

#984 add docker compose
  docker-compose.yml
  src/Dockerfile
  src/Dockerfile.wordpress
  src/frontend/package.json
  src/frontend/src/Header/Menu/MenuButton.tsx
  src/frontend/src/ParamFields/index.tsx
  src/frontend/tsconfig.json
Labels: Implementierung

#993 Fehler beim Erstellen der Dokumentation
  README.md
  src/visuanalytics/requirements-dev.txt
Labels: bug, dependencies

#1002 Projects Bord Automatisation verbesserungen
  .github/workflows/projects-bord-automatisation.yml
Labels: Organisation
